### PR TITLE
adding с.новым.годом.рф

### PR DESCRIPTION
**Pull request by cjerrington**
Noticed this new site on my google analytics account. Looks similar to the other spam sites. Most of my referrals tend to be from Facebook and Twitter, not referral spam sites.

### CODE REVIEW

**Comment by lembitk** [comment]
Please note that [`годом.рф` is already on the list](https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt#L334) (and its subdomain `с.новым.годом.рф` should thus get blocked just fine).

**Comment by cjerrington** [comment]
Awesome! That works perfectly then! 

Thanks!

**Comment by lembitk** [comment]
@cjerrington could you maybe close this PR, to keep the repo tidier? Just a thought.. Thanks.

**Comment by mnapoli** [comment]
Closed :)

**Pull request closed without merging**
