### PR TITLE
Create nginx-conf.sh

### PR DESCRIPTION
**Pull request by lolwhoami**
creating config file for nginx

### CODE REVIEW

**Comment by mattab** [comment]
Hi @lolwhoami 

Thanks for the suggestion. We don't want to merge this in the project to keep it simple, but maybe we can leave this Pull request opened as it may give others inspiration :+1:

**Comment by schalkt** [comment]
+1 to merge and i think it would be good an apache-conf.sh too

**Comment by chauncey-garrett** [comment]
@schalkt see [chauncey-garrett/referral-spam-blacklist](https://github.com/chauncey-garrett/referral-spam-blacklist) which is my solution to the problem. It takes a similar (but independently developed) approach to @lolwhoami's solution here. If you'd like an apache conf file, open an issue with an example and I'll incorporate it into the repo.

**Comment by almer-t** [comment]
Some Python tools that use this blacklist:
https://github.com/almer-t/tools/tree/master/referrer_spam

**Pull request closed without merging**
