### PR TITLE
Add social-traffic-5.xyz

### PR DESCRIPTION
**Pull request by lembitk**
Adding `social-traffic-5.xyz`, a domain spamming several GA accounts I manage.

### CODE REVIEW

**Comment by spmedia** [comment]
+1

**Comment by mnapoli** [comment]
Thanks could you rebase please? Or I could add it manually too, let me know.

**Comment by lembitk** [comment]
@mnapoli, this should merge fine now.

**Comment by mnapoli** [comment]
Thanks!

**Pull request merged**
