### PR TITLE
Add online247.ml

### PR DESCRIPTION
**Pull request by lembitk**
Adding online247.ml, a domain seen spamming couple of GA accounts I manage.

### CODE REVIEW

**Comment by mnapoli** [comment]
Unfortunately all the pull request you created today contain multiple commits (this PR contains also #228 for example). Could you rebase or reopen a new pull request with a single commit if you don't know how to rebase?

**Comment by lembitk** [comment]
Thanks for pointing this out. Let me see what I can do.

**Comment by lembitk** [comment]
Hi @mnapoli, I've updated this PR, and also #227 and #228. Thanks again :bow:

**Comment by mnapoli** [comment]
Perfect thank you, now we'll be waiting for confirmation from a second person before merging this.

**Comment by lembitk** [comment]
Closing, as haven't seen this domain anymore (and apparently others haven't too).

**Pull request closed without merging**
