### PR TITLE
Add more spammers

### PR DESCRIPTION
**Pull request by lucaspetter**
Spammers that have visited my site over the past year, all with 100% bounce, none of which actually link to my site. Alphabetized.
```
adspart.com
adventureparkcostarica.com
baixar-musicas-gratis.com
balitouroffice.com
break-the-chains.com
cezartabac.ro
civilwartheater.com
coderstate.com
connectikastudio.com
demenageur.com
descargar-musica-gratis.net
egovaleo.it
ekto.ee
livefixer.com
rightenergysolutions.com.au
semalt.semalt.com
seopub.net
seo-smm.kz
sharebutton.net
soaksoak.ru
uzungil.com
wmasterlead.com
```

### CODE REVIEW

**Comment by mattab** [comment]
We realistically won't get +1 for all those so I'm merging. Gut feeling leds me to believe they are spammers.

**Comment by lucaspetter** [comment]
Thanks!

**Comment by mnapoli** [comment]
Please keep in mind that once a site goes in the blacklist, it will be very hard to get it out of it. Whereas adding one is very easy. What I mean is that it's better to be too careful and not block a few spammers for a week or two rather than blocking a valid site forever.

If we make a few mistakes, the whole spammers list could loose its value.

In the list, `semalt.semalt.com` is a duplicate of `semalt.com`. Some other websites look like legitimate websites, blocking them could be very bad for them, we have a responsibility towards the community (even more if the list is used outside Piwik). At least one website also doesn't exist anymore (`connectikastudio.com`), I haven't tested them all.

**Comment by lucaspetter** [comment]
@mnapoli 

> What I mean is that it's better to be too careful and not block a few spammers for a week or two rather than blocking a valid site forever.

I agree, it doesn't hurt to wait a week or two for discussion from others.

> In the list, `semalt.semalt.com` is a duplicate of `semalt.com`.

Are you saying that domains in the blacklist cover all subdomains too? If so, we should put a note about this under Contributing in the README.md file and remove `semalt.semalt.com`. I could make a new pull request for this.

> Some other websites look like legitimate websites, blocking them could be very bad for them, we have a responsibility towards the community (even more if the list is used outside Piwik).

Being a legitimate website is no excuse for spamming the logs/analytics of other random websites all over the Internet. While some sites may indeed be legitimate businesses with no malicious intentions, such as `adventureparkcostarica.com` or `balitouroffice.com`, they're still using illegitimate marketing techniques to create traffic to their sites, whether they're aware of it or not. Some businesses may have hired a 3rd party company to do their marketing, having no idea that the marketers are using referrer spam in their techniques. Also, because referrers can be easily forged by anyone, it may not be the site owners who are doing the spamming, it could be a competitor who wants to damage their reputation.

**Comment by mnapoli** [comment]
> Are you saying that domains in the blacklist cover all subdomains too?

I believe so, @mattab can confirm?

> Being a legitimate website is no excuse for spamming the logs/analytics of other random websites all over the Internet.

I definitely agree :) However from the data we have here, some domains could end up being blacklisted because once there was a visit with a bounce for somebody (today you, tomorrow somebody else with another pull request).

If we take the analogy of email spams: you would want a spam filter to filter out the spam. But the most important thing is that it should not block valid emails. It's way more important than having one or two spams not detected. It's the same here. But our situation is even harder than for spam filters: it's almost impossible for us to know if we have false positive, so we definitely should avoid any possible mistakes.

**Comment by mattab** [comment]
in Piwik we do sub-string matching on the domain name, so `semalt.com` is enough to block all `*.semalt.com` referrers - @lucaspetter feel free to add a note under Contributing

**Comment by lucaspetter** [comment]
Okay, note about subdomains added to README in #46.

**Pull request merged**
