### PR TITLE
Adding manta.com

### PR DESCRIPTION
**Pull request by timetolive**
This has been spamming our site

### CODE REVIEW

**Comment by spmedia** [comment]
Manta.com is a huge local directory website. Not spam imo.

**Comment by timetolive** [comment]
They appear to be a legit digital marketing business, but they are definitely spamming my website like the others that are performing "referrer spam" that throws off my analytics.

Why would you say they should not be blocked when they do that?

**Comment by spmedia** [comment]
They are a legit local directory website I interact with weekly when doing
local seo.

They do no engage in referrer spam.

I have access to 100+ different websites GA and Piwik Analytics accounts
and they do not do this.

You also listed duckduckgo incorrectly as referral spam so imo you don't
know what you're talking about here. ;)

**Comment by timetolive** [comment]
Manners.  I have no ego invested here, just trying to do my part to improve the world for others.  

I see that their activity did add to a listing they have.  I stand corrected.

**Comment by mnapoli** [comment]
Let's try to be friendly and not push away contributors :)

**Pull request closed without merging**
