### PR TITLE
Update spammers.txt

### PR DESCRIPTION
**Pull request by cfconsultancy**
More referrer and bad bots

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you for the contribution. Please note that `100dollars-seo.com` is already in the list. Also we want to keep the list sorted.

**Comment by cfconsultancy** [comment]
Made a new request

**Comment by mnapoli** [comment]
I've just added `seoanalyses.com` manually (see #96). FYI bulk pull requests require that we validate all domains at once. Single changes are easier to merge since we only need to validate one domain.

**Comment by mnapoli** [comment]
I'll be closing this PR then since you've opened #95

**Pull request closed without merging**
