### PR TITLE
Add lumb.co

### PR DESCRIPTION
**Pull request by futureweb**

### CODE REVIEW

**Comment by mnapoli** [comment]
Duplicates #514

**Comment by futureweb** [comment]
Hi @mnapoli,

it's NO duplicate ...

lomb.co != lumb.co

Plese reopen

thx
Andreas

**Comment by mnapoli** [comment]
Apologies, the amount of PRs to review doesn't make it easy.

**Comment by futureweb** [comment]
I can imagine the amount of work this is - thx & keep up the great work! ;-)

**Pull request merged**
