### PR TITLE
Update spammers.txt

### PR DESCRIPTION
**Pull request by HelgeSverre**
Added ilikevitaly.com

Usually presents itself like this:
``` how.to.travel.and.make.money.with.maps.ilikevitaly.com ```

### CODE REVIEW

**Comment by spmedia** [comment]
+1

**Comment by mnapoli** [comment]
Hi, could you keep the list sorted per the contributing guidelines?

**Comment by lembitk** [comment]
+1

**Comment by mnapoli** [comment]
Sorry I didn't see you pushed a new commit, merging!

**Pull request merged**
