### PR TITLE
100dollar SEO

### PR DESCRIPTION
**Pull request by Firesphere**
New referralspammer.

### CODE REVIEW

**Comment by Firesphere** [comment]
I see I'm not the first to mention 100dollar(s) SEO.

**Comment by mnapoli** [comment]
Yep, in that case add a `+1` in the issue so that we know that other people confirmed it as a spammer. I've added the domain to the list thanks.

**Comment by Firesphere** [comment]
Will do. Noticed the first PR after creating my own. Next time, I'll read first and PR later ;)

**Comment by mnapoli** [comment]
No worries thanks for contributing :)

**Pull request closed without merging**
