### PR TITLE
Add law-six.xyz

### PR DESCRIPTION
**Pull request by ricvelozo**
Domain registered on 2016-06-30; hit 25 times my website yesterday.

### CODE REVIEW

**Comment by spmedia** [comment]
+1

**Comment by mnapoli** [comment]
Thanks, this pull request has conflicts, could you rebase it?

**Comment by ricvelozo** [comment]
Done.

**Comment by mnapoli** [comment]
Oh now it has 15 commits! It should only contain one for the domain you are adding.

**Comment by ricvelozo** [comment]
Done.

**Comment by mnapoli** [comment]
All good thanks!

**Pull request merged**
