### PR TITLE
Added two new columns: domain category and whether the domain is currently live or not

### PR DESCRIPTION
**Pull request by alexanderdean**
Hey @mattab ! I think this is a great initiative. I've gone through and added categories and whether the domain is currently live or not to each entry.

I'm not wedded to the pipe-delim format or anything, feel free to adjust as you see fit...

### CODE REVIEW

**Comment by mnapoli** [comment]
Hi, thanks for taking the time to do this. However I'm not sure this is necessary. For example in Piwik we have no use of those information, and it makes the file a little harder to parse. Having a simple list that anything can read is really appreciable.

**Comment by hakunin** [comment]
I was about to ask if Piwik uses that info in any way. The whole reason I watch this project is to feed my blacklist with those domains.

**Comment by mnapoli** [comment]
Yes in any case I'm afraid we can't break the current format for people relying on it (just like Piwik is).

**Comment by alexanderdean** [comment]
Hey guys - ah got it. Feel free to close. I think we will approach this a different way in Snowplow anyway (we will probably just add a spam section to our referer parser project) [1] [2]

[1] https://github.com/snowplow/snowplow/issues/1697#issuecomment-103809566
[2] https://github.com/snowplow/snowplow/issues/1697#issuecomment-103809566

**Comment by mnapoli** [comment]
I understand. Thanks for the links

**Pull request closed without merging**
