### PR TITLE
traffic2money.com, e-buyeasy.com

### PR DESCRIPTION
**Pull request by richardpoyner**
traffic2money.com, e-buyeasy.com

### CODE REVIEW

**Comment by brodjustice** [comment]
Just to give my +1 for traffic2money.com, hit us yesterday: 76% of all traffic, 97% bounce rate, all traffic from Russia, and like so may of these spam sites the registrant is at Nobby Beach, Queensland, AU.

**Comment by Raydian51** [comment]
Hello spam warriors,


Does anyone know if there is a way to add filters to several websites under
one Google analytic account?

Kind Regards
*Raynaldo Perez*

*raynaldo@*submitexpress.com <raynaldo@submitexpress.com> | 818-567-3030 | EX.
231  |
*Submit Express, Inc  - www.submitexpress.com
<http://www.submitexpress.com>*



<http://www.submitexpress.com/>

**Comment by appeltauer** [comment]
Hi Ray,

I've made a tool that installs filters into Google Analytics and automatically updates them for you.

See https://digmato.com/google-analytics/referral-spam-filter-buy

Kind Regards,
Roman Appeltauer



S pozdravem,
Roman Appeltauer
+420 720 758 983

**Comment by mnapoli** [comment]
I have added manually traffic2money.com in d8144f7436afadbb35639e30e7e6331dd3cec989 (because it was validated twice in here and also in #89).

Waiting for confirmation to merge e-buyeasy.com.

Thank you

**Comment by mnapoli** [comment]
The second domain was confirmed in #91, it has been added to the list. Thanks!

**Pull request closed without merging**
