### PR TITLE
Add nufaq.com

### PR DESCRIPTION
**Pull request by PickledDragon**
Based on GA data

### CODE REVIEW

**Comment by appeltauer** [comment]
+1
I'd suggest to list just the **nufaq.com** (it has the same content as website-stealer.nufaq.com)

**Comment by spmedia** [comment]
+1

website-stealer.nufaq.com - Hits started coming in Dec 19th on GA.

**Comment by mnapoli** [comment]
+1 for blocking `nufaq.com` only, @PickledDragon if you can update your pull request?

**Comment by PickledDragon** [comment]
Updated to 2nd level TLD

**Comment by mnapoli** [comment]
:+1: thanks!

**Pull request merged**
